version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stylehub-frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules # Evita sobreescribir dependencias internas
    environment:
      - NODE_ENV=development
